version: '3.5'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      network: app_default
    ports:
      - 4000:80
      - 4001:443
networks:
  default:
    name: app_default